services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: "docker"
      POSTGRESQL_PASSWORD: "docker"
      POSTGRESQL_DATABASE: "connect"
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "docker"
